name: omr_scanner_flutter_android_example
description: "Demonstrates how to use the omr_scanner_flutter_android plugin."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  omr_scanner_flutter_android:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

