name: omr_scanner_flutter_android
description: "A new Flutter plugin project."
version: 0.2.4
homepage:

environment:
  sdk: ^3.6.1
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.prayag.omr_scanner_flutter_android
        pluginClass: OmrScannerFlutterAndroidPlugin